#! /bin/sh

# 启动 sxhkd（如果未运行）
pgrep -x sxhkd >/dev/null || sxhkd &

dunst &
fcitx5 &
# 设置桌面
bspc monitor -d I II III IV V VI VII VIII IX X

# 配置边框和间隔
bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# 规则配置
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Nord 配色方案
bspc config active_border_color '#81A1C1'   # 冷色调
bspc config inactive_border_color '#4C566A' # 灰色
bspc config focused_border_color '#88C0D0'  # 亮蓝色
bspc config background_color '#2E3440'      # 背景色
bspc config foreground_color '#D8DEE9'      # 前景色

# 启动 picom 并使用 glx 后端
picom --backend glx --config ~/.config/picom/picom.conf &

#polybar
~/.config/polybar/launch.sh &

~/.config/bspwm/wallpaper.sh &

pulseaudio &

nm-applet &
